on:
  schedule:
  - cron: '*/30 * * * *'
  workflow_dispatch:
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
        git clone https://github.com/jingyu9575/scoop.git
        git config --global user.name AutoUpdate
        git config --global user.email autoupdate@qw.thucfb.com
        ./scoop/bin/auto-pr.ps1 -Dir bucket -Upstream "https://${env:GITHUB_ACTOR}:$env:GITHUB_TOKEN@github.com/$env:GITHUB_REPOSITORY.git:master" -Push -SkipUpdated
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
